version: "3.5"
networks:
  default:
    labels:
      - dev.warden.environment.name=${WARDEN_ENV_NAME}
      - dev.warden.environment.type=${WARDEN_ENV_TYPE}

services:
  nginx:
    hostname: "${WARDEN_ENV_NAME}-nginx"
    image: quay.io/warden/nginx:${NGINX_VERSION:-1.16}
    environment:
      - NGINX_TEMPLATE=magento1.conf
    depends_on:
      - php-fpm
    volumes:
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.priority=1
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.rule=
          HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`) || Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-nginx.loadbalancer.server.port=80

  php-fpm:
    volumes:
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated

  php-debug:
    volumes:
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated

  db:
    hostname: "${WARDEN_ENV_NAME}-mariadb"
    image: quay.io/warden/mariadb:${MARIADB_VERSION:-10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}
    command:
      - mysqld
      - --max_allowed_packet=1024M
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    hostname: "${WARDEN_ENV_NAME}-redis"
    image: quay.io/warden/redis:${REDIS_VERSION:-5.0}

  mailhog:
    hostname: "${WARDEN_ENV_NAME}-mailhog"
    image: quay.io/warden/mailhog:${MAILHOG_VERSION:-1.0}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-mailhog.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-mailhog.rule=Host(`mailhog.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-mailhog.loadbalancer.server.port=8025

volumes:
  dbdata:
