version: "3.5"
services:
  nginx:
    hostname: "${WARDEN_ENV_NAME}-nginx"
    image: quay.io/warden/nginx:${NGINX_VERSION:-1.16}
    environment:
      - NGINX_PUBLIC=/pub
      - NGINX_TEMPLATE=magento2.conf
    depends_on:
      - php-fpm
    labels:
      - traefik.enable=${BYPASS_VARNISH:-false}
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.priority=2
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.rule=HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-nginx.loadbalancer.server.port=80
    networks:
      - warden
      - default

  php-fpm:
    hostname: "${WARDEN_ENV_NAME}-php-fpm"
    image: quay.io/warden/php-fpm:${PHP_VERSION:-7.3}-magento2
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - NODE_VERSION=${NODE_VERSION:-10}
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-livereload.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-livereload.priority=2
      - traefik.http.routers.${WARDEN_ENV_NAME}-livereload.rule=
          HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`)
            && (Path(`/livereload.js`) || Path(`/livereload`))
      - traefik.http.routers.${WARDEN_ENV_NAME}-livereload.service=${WARDEN_ENV_NAME}-livereload
      - traefik.http.services.${WARDEN_ENV_NAME}-livereload.loadbalancer.server.port=35729
    networks:
      - default
      - warden

  php-debug:
    hostname: "${WARDEN_ENV_NAME}-php-debug"
    image: quay.io/warden/php-fpm:${PHP_VERSION:-7.3}-magento2-debug
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - NODE_VERSION=${NODE_VERSION:-10}
      - PHP_IDE_CONFIG=serverName=${WARDEN_ENV_NAME}-docker
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    networks:
      - default
      - warden

volumes:
  dbdata:
  esdata:

networks:
  warden:
    external: true
