version: "3.5"
services:
  php-fpm:
    depends_on:
      - db

  php-debug:
    depends_on:
      - db

  db:
    hostname: "${WARDEN_ENV_NAME}-mariadb"
    image: quay.io/warden/mariadb:${MARIADB_VERSION:-10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}
    command:
      - mysqld
      - --max_allowed_packet=1024M
      - --explicit_defaults_for_timestamp=on
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - warden
      - default

volumes:
  dbdata:
  esdata:

networks:
  warden:
    external: true
