version: "3.5"
services:
  php-blackfire:
    hostname: "${WARDEN_ENV_NAME}-php-blackfire"
    image: davidalger/warden:mage2-fpm-${PHP_VERSION:-7.3}-blackfire
    depends_on:
      - db
    networks:
      - warden
      - default

  blackfire-agent:
    hostname: "${WARDEN_ENV_NAME}-blackfire-agent"
    image: blackfire/blackfire:latest
    environment:
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN}
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
    networks:
      - warden
      - default
