version: "3.5"
services:
  nginx:
    hostname: nginx
    image: davidalger/warden:nginx-${NGINX_VERSION:-1.16}-alpine
    environment:
      - NGINX_TEMPLATE=magento1.conf
    depends_on:
      - db
      - php-fpm
    volumes:
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}
    networks:
      - warden
      - default

  php-fpm:
    hostname: php-fpm
    image: davidalger/warden:mage1-fpm-${PHP_VERSION:-7.2}
    depends_on:
      - db
    volumes:
      - ~/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
      - ~/.composer:/home/www-data/.composer:delegated
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated

  php-debug:
    hostname: php-debug
    image: davidalger/warden:mage1-fpm-${PHP_VERSION:-7.2}-debug
    environment:
      - PHP_IDE_CONFIG=serverName=${WARDEN_ENV_NAME}-docker
    depends_on:
      - db
    volumes:
      - ~/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
      - ~/.composer:/home/www-data/.composer:delegated
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated

  db:
    hostname: mariadb
    image: mariadb:${MARIADB_VERSION:-10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}
    command:
      - mysqld
      - --max_allowed_packet=1024M
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - warden
      - default

  redis:
    hostname: redis
    image: redis:${REDIS_VERSION:-5.0}-alpine

  mailhog:
    hostname: mailhog
    image: mailhog/mailhog:${MAILHOG_VERSION:-v1.0.0}
    labels:
      - traefik.enable=true
      - traefik.port=8025
      - traefik.frontend.rule=Host:mailhog.${TRAEFIK_DOMAIN}
    networks:
      - warden
      - default

volumes:
  dbdata:

networks:
  warden:
    external: true
