version: "3.5"
services:
  traefik:
    container_name: traefik
    image: traefik
    command: --api --docker --docker.domain=test
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
    volumes:
      - ~/.warden/etc/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ~/.warden/ssl/certs:/etc/ssl/certs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - traefik.port=8080
    restart: always

  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - proxy
    labels:
      - traefik.port=9000
    restart: always

volumes:
  portainer:

networks:
  default:
    name: warden_default
  proxy:
    name: warden_proxy
