version: "3.5"
services:
  nginx:
    environment:
      - NGINX_PUBLIC=/pub
      - NGINX_TEMPLATE=magento2.conf
    labels:
      - traefik.enable=${BYPASS_VARNISH:-false}
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.priority=2

  varnish:
    hostname: "${WARDEN_ENV_NAME}-varnish"
    image: quay.io/warden/varnish:${VARNISH_VERSION:-6.0}
    depends_on:
      - nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-varnish.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-varnish.priority=1
      - traefik.http.routers.${WARDEN_ENV_NAME}-varnish.rule=
          HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`) || Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-varnish.loadbalancer.server.port=80

  php-fpm:
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-livereload.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-livereload.priority=2
      - traefik.http.routers.${WARDEN_ENV_NAME}-livereload.rule=
          (HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`) || Host(`${TRAEFIK_DOMAIN}`))
            && (Path(`/livereload.js`) || Path(`/livereload`))
      - traefik.http.routers.${WARDEN_ENV_NAME}-livereload.service=${WARDEN_ENV_NAME}-livereload
      - traefik.http.services.${WARDEN_ENV_NAME}-livereload.loadbalancer.server.port=35729

  db:
    hostname: "${WARDEN_ENV_NAME}-mariadb"
    image: quay.io/warden/mariadb:${MARIADB_VERSION:-10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}
    command:
      - mysqld
      - --max_allowed_packet=1024M
      - --explicit_defaults_for_timestamp=on
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  esdata:
