name: Build documentation
on:
  push:
    paths:
      - docs/**
      - .github/workflows/build-documentation.yml

jobs:
  build-documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: "docs/"
      - uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs/_build/html/
