name: Docker Image Varnish
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - version
      - images/.trigger
      - images/varnish/**
    branches:
      - develop
jobs:
  varnish:
    name: Varnish

    strategy:
      fail-fast: false
      matrix:
        version:
          - "6.5"
          - "6.6"
          - "7.0"
        include:
          - version: "6.0"
            lts: true

    runs-on: ubuntu-latest
    steps:
      - name: Configure RPM repository
        if: ${{ matrix.lts == true }}
        run: echo "VARNISH_REPO=$(echo ${{ matrix.version }} | tr -d .)lts" >> $GITHUB_ENV

      - name: Configure RPM repository
        if: ${{ matrix.lts == true }}
        run: echo "VARNISH_REPO=$(echo ${{ matrix.version }} | tr -d .)" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (amd64, arm64)
        uses: docker/build-push-action@v2
        with:
          context: images/varnish/context
          file: images/varnish/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: VARNISH_REPO=${VARNISH_REPO}
          push: true
          tags: docker.io/wardenenv/varnish:${{ matrix.version }}
